all: bin/ShowGame.class bin/GLaDOS.class bin/AlwaysWin.class

bin/ShowGame.class: src/ShowGame.java
	javac src/ShowGame.java -sourcepath src/ -d bin

bin/AlwaysWin.class: src/AlwaysWin.java
	javac src/AlwaysWin.java -sourcepath src/ -d bin

bin/GLaDOS.class: src/GLaDOS.java
	javac src/GLaDOS.java -sourcepath src/ -d bin
