all: bin/ShowGame.class bin/GLaDOS.class bin/GLaDiOS.class

bin/ShowGame.class: src/ShowGame.java
	javac src/ShowGame.java -sourcepath src/ -d bin

bin/GLaDOS.class: src/GLaDOS.java
	javac src/GLaDOS.java -sourcepath src/ -d bin

bin/GLaDiOS.class: src/GLaDiOS.java
	javac src/GLaDiOS.java -sourcepath src/ -d bin
