all: bin/ShowGame.class bin/GLaDOS.class

bin/ShowGame.class: src/ShowGame.java
	javac src/ShowGame.java -sourcepath src/ -d bin

bin/GLaDOS.class: src/GLaDOS.java
	javac src/GLaDOS.java -sourcepath src/ -d bin
